import {getServerSession} from 'next-auth';

import Layout from "../components/Layout";
import Provider from "../provider/sessionProvider";
import {options} from "./api/auth/[...nextauth]/options";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(options);

  return (
    <html lang="en">
      <Provider session={session}>
        <body>
          <Layout>
            {children}
          </Layout>
        </body>
      </Provider>
    </html>
  )
}
